#line 2 "/home/wangyiming/db2025-yoursql/src/parser/lex.yy.cpp"

#line 4 "/home/wangyiming/db2025-yoursql/src/parser/lex.yy.cpp"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

#ifdef yyget_lval
#define yyget_lval_ALREADY_DEFINED
#else
#define yyget_lval yyget_lval
#endif

#ifdef yyset_lval
#define yyset_lval_ALREADY_DEFINED
#else
#define yyset_lval yyset_lval
#endif

#ifdef yyget_lloc
#define yyget_lloc_ALREADY_DEFINED
#else
#define yyget_lloc yyget_lloc
#endif

#ifdef yyset_lloc
#define yyset_lloc_ALREADY_DEFINED
#else
#define yyset_lloc yyset_lloc
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 72
#define YY_END_OF_BUFFER 73
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[254] =
    {   0,
        0,    0,    0,    0,   73,   71,    6,    7,    7,   71,
       65,   65,   62,   63,   64,   66,   65,   65,   70,   70,
       70,   70,   70,   70,   70,   70,   70,   70,   70,   70,
       70,   70,   70,   70,   70,   70,   70,   70,    3,    4,
        0,    0,    6,    7,    0,   68,   66,    5,    1,   67,
       60,   61,   59,   70,   70,   70,   47,   70,   70,   52,
       70,   70,   70,   70,   70,   70,   70,   70,   70,   70,
       70,   70,   70,   70,   70,   70,   70,   70,   70,   70,
       37,   70,   70,   70,   70,   70,   70,   70,   70,   70,
       70,   70,    2,    0,    5,    5,    5,   67,   70,   35,

       70,   53,   46,   70,   70,   70,   70,   70,   70,   70,
       70,   70,   70,   70,   70,   70,   70,   70,   70,   70,
       70,   70,   70,   30,   70,   70,   70,   43,   44,   70,
       70,   70,   70,   25,   70,   70,   45,   70,   70,   70,
       70,   70,    0,    5,   70,   39,   70,   31,   70,   70,
       70,   33,   70,   17,   16,   70,   40,   70,   70,   70,
       22,   70,   70,   41,   70,   70,   19,   36,   70,   28,
       70,   70,   70,   38,    8,   70,   70,   57,   70,   70,
       70,   69,    5,   11,    9,   70,   42,   70,   70,   70,
       70,   58,   32,   49,   70,   34,   70,   51,   50,   70,

       70,   70,   15,   70,   70,   23,    5,   10,   14,   21,
       70,   70,   48,   18,   70,   26,   70,   13,   24,   20,
       70,   27,   70,   70,   70,   70,   12,   70,   70,   70,
       70,   70,   70,   70,   70,   70,   70,   70,   70,   70,
       70,   70,   70,   70,   70,   70,   54,   70,   70,   55,
       70,   56,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    1,    1,    1,    1,    1,    5,    6,
        7,    8,    9,   10,   11,   12,   13,   14,   14,   14,
       14,   14,   14,   14,   14,   14,   14,    1,   15,   16,
       17,   18,    1,    1,   19,   20,   21,   22,   23,   24,
       25,   26,   27,   28,   29,   30,   31,   32,   33,   34,
       35,   36,   37,   38,   39,   40,   41,   42,   43,   35,
        1,    1,    1,    1,   44,    1,   45,   46,   47,   48,

       49,   50,   51,   52,   53,   54,   55,   56,   57,   58,
       59,   60,   35,   61,   62,   63,   64,   65,   66,   67,
       68,   35,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[69] =
    {   0,
        1,    2,    3,    2,    2,    2,    2,    1,    1,    1,
        1,    1,    1,    1,    2,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1
    } ;

static const flex_int16_t yy_base[260] =
    {   0,
        0,    0,  132,  130,  134,  120,  126, 1779,  123,  120,
     1779,  111,   57,   61,   62,   64,   65,   67,   84,  149,
       84,   86,  121,  150,  148,  132,  164,  171,  133,  192,
      204,  201,  205,  232,  242,  233,  269,  276, 1779,  106,
      106,   68,  112, 1779,  108, 1779,   74,  327,   99,  127,
       91,   87,   86,  240,  297,  300,  324,  327,  332,  292,
      339,  354,  331,  363,  386,  371,  398,  410,  415,  413,
      442,  444,  446,  474,  483,  475,  451,  490,  473,  504,
      506,  534,  536,  537,  538,  546,  567,  576,  578,  585,
      600,  589, 1779,   75,  657,    0,  669,   94,  642,  637,

      665,  644,  666,  674,  677,  698,  705,  713,  676,  681,
      729,  734,  741,  736,  737,  752,  773,  780,  785,  783,
      796,  784,  812,  817,  835,  819,  847,  834,  848,  851,
      856,  858,  865,  886,  887,  894,  897,  915,  898,  925,
      933,  937,  240, 1002,  972,  926,  979,  976,  989,  980,
     1003, 1007, 1011, 1010, 1038, 1039, 1040, 1049, 1042, 1073,
     1050, 1078, 1077, 1080, 1082, 1111, 1090, 1114, 1121, 1119,
     1142, 1151, 1152, 1143, 1153, 1181, 1182, 1183, 1184, 1186,
     1193,   79, 1251, 1194, 1216, 1237, 1221, 1225, 1249, 1253,
     1254, 1265, 1276, 1281, 1286, 1283, 1304, 1297, 1313, 1315,

     1325, 1348, 1336, 1343, 1347, 1357, 1415, 1364, 1380, 1385,
     1395, 1403, 1408, 1413, 1426, 1417, 1435, 1431, 1444, 1447,
     1465, 1449, 1477, 1488, 1481, 1495, 1493, 1517, 1516, 1528,
     1524, 1532, 1545, 1576, 1568, 1578, 1583, 1606, 1579, 1607,
     1610, 1634, 1638, 1639, 1617, 1666, 1649, 1661, 1673, 1671,
     1689, 1700, 1779, 1768,   89, 1771,   80, 1774, 1776
    } ;

static const flex_int16_t yy_def[260] =
    {   0,
      253,    1,  254,  254,  253,  255,  253,  253,  253,  256,
      253,  255,  255,  255,  255,  255,  255,  255,  257,  257,
       20,   20,   20,   20,   20,   20,   20,   20,   20,   20,
       20,   20,   20,   20,   20,   20,   20,   20,  253,  253,
      255,  255,  253,  253,  256,  253,  255,  258,  255,  255,
      255,  255,  255,   20,   20,   20,   20,   20,   20,   20,
       20,   20,   20,   20,   20,   20,   20,   20,   20,   20,
       20,   20,   20,   20,   20,   20,   20,   20,   20,   20,
       20,   20,   20,   20,   20,   20,   20,   20,   20,   20,
       20,   20,  253,  255,  258,  259,  258,  255,   20,   20,

       20,   20,   20,   20,   20,   20,   20,   20,   20,   20,
       20,   20,   20,   20,   20,   20,   20,   20,   20,   20,
       20,   20,   20,   20,   20,   20,   20,   20,   20,   20,
       20,   20,   20,   20,   20,   20,   20,   20,   20,   20,
       20,   20,  255,  258,   20,   20,   20,   20,   20,   20,
       20,   20,   20,   20,   20,   20,   20,   20,   20,   20,
       20,   20,   20,   20,   20,   20,   20,   20,   20,   20,
       20,   20,   20,   20,   20,   20,   20,   20,   20,   20,
       20,  255,  258,   20,   20,   20,   20,   20,   20,   20,
       20,   20,   20,   20,   20,   20,   20,   20,   20,   20,

       20,   20,   20,   20,   20,   20,  258,   20,   20,   20,
       20,   20,   20,   20,   20,   20,   20,   20,   20,   20,
       20,   20,   20,   20,   20,   20,   20,   20,   20,   20,
       20,   20,   20,   20,   20,   20,   20,   20,   20,   20,
       20,   20,   20,   20,   20,   20,   20,   20,   20,   20,
       20,   20,    0,  253,  253,  253,  253,  253,  253
    } ;

static const flex_int16_t yy_nxt[1848] =
    {   0,
        6,    7,    8,    9,   10,   11,   11,   12,   13,   12,
       14,   12,   15,   16,   11,   17,   12,   18,   19,   20,
       21,   22,   23,   24,   25,   26,   27,   28,   29,   30,
       31,   29,   32,   29,   29,   33,   34,   35,   36,   37,
       38,   29,   29,    6,   19,   20,   21,   22,   23,   24,
       25,   26,   27,   28,   29,   30,   31,   29,   32,   29,
       33,   34,   35,   36,   37,   38,   29,   29,   42,   49,
       47,   48,   42,   42,   47,   50,   42,   47,   42,   42,
       54,   51,   52,   53,   41,   50,   42,   47,   94,   41,
       42,   41,   41,   41,   41,   42,   41,   42,   42,   41,

       41,   41,   42,   55,   64,   42,   54,   98,   65,   61,
       42,  143,   46,   43,   94,   56,   62,   42,   93,   63,
       57,   66,   42,   58,   46,   44,   54,   43,   54,   55,
       64,   42,   54,  253,   65,   61,  143,   40,   42,   40,
       98,   56,   62,   54,   63,   57,   66,   94,   58,   41,
       73,   54,   67,   54,   74,   54,   41,   41,   41,   41,
       42,   41,   68,   54,   41,   41,   41,  253,   69,   54,
       54,   59,   54,   94,   54,   54,   73,  253,   67,   70,
       74,   54,  253,   72,  253,   71,   54,   68,   54,  253,
       54,   60,   54,   54,   69,   75,   54,   59,   54,   54,

       54,  253,  253,   76,  253,   70,   54,  253,   72,  253,
       71,  253,   54,   54,   54,   54,   60,   54,   77,   54,
      253,   75,   79,   54,   78,  253,   54,   54,  253,   76,
       80,   54,   81,  253,   54,  253,   82,   83,   54,  253,
       54,  253,  253,   54,   77,  253,   54,   54,   79,   54,
       78,   42,   54,   54,   84,   54,   80,   85,   81,   54,
       88,   82,   54,   83,   54,  253,   90,  253,   54,   86,
       87,   54,   54,  253,   54,   54,  253,   89,  253,  182,
       84,   54,   54,   85,   54,  253,   88,   91,   54,  253,
       54,   54,   90,  253,   86,   87,  253,  253,   54,   54,

       54,   92,   89,  253,  182,  253,  253,   54,  253,   54,
      253,   54,  253,   91,   54,  253,  253,   54,   54,   54,
      253,  100,   54,  253,   54,  253,  253,   92,   96,   99,
       96,   96,   96,   96,   54,  253,   54,  101,   97,   54,
       54,   96,   54,   54,  102,   54,   54,  100,   54,   54,
      253,  103,  253,  108,   54,   99,  104,  105,  253,   54,
      253,   54,  101,  253,   54,  253,   54,   54,  253,   54,
      102,  253,   54,   54,   54,   54,   54,  103,  253,  108,
       54,   54,  104,  105,  106,   54,  253,   54,  253,  253,
      253,   54,  107,   54,   54,  253,   54,  253,   54,   54,

      109,  253,   54,  112,  253,   54,   54,  253,   54,  253,
      106,   54,  253,   54,  253,  110,  113,  107,  253,   54,
       54,   54,  111,  253,  253,  109,  253,  253,   54,  112,
       54,  253,   54,  253,   54,   54,  114,   54,   54,  253,
       54,  110,  113,  115,  116,  117,   54,  111,  253,  253,
      253,  253,   54,   54,  253,   54,  253,   54,   54,  253,
      253,   54,  114,   54,   54,   54,   54,  253,   54,  115,
      116,  117,  253,   54,  118,  253,  119,   54,  253,  253,
       54,  126,   54,  253,   54,  120,   54,  253,   54,  253,
       54,  253,   54,   54,   54,   54,   54,   54,  253,   54,

      118,  125,  119,  121,  122,   54,  253,  126,  127,   54,
      120,   54,   54,   54,  128,   54,   54,   54,   54,  123,
      124,   54,   54,   54,  253,   54,   54,  125,   54,  121,
      122,   54,   54,  253,  127,  129,  253,  253,   54,  128,
       54,   54,   54,  253,  123,  124,   54,  253,   54,  253,
       54,  253,   54,  253,   54,  130,   54,   54,   54,   54,
       54,  129,  253,  253,  136,  131,  132,  133,   54,  253,
      135,   54,  253,   54,  134,  253,   54,  253,   54,   54,
       54,  130,   54,  253,   54,   54,   54,  253,   54,   54,
      136,  131,  132,  133,   54,  138,  135,  137,   54,  134,

       54,   54,  253,   54,   54,   54,  140,   54,  253,   54,
      253,  142,  253,   54,  253,   54,  139,  253,   54,  253,
       54,  138,   54,  137,   54,  253,   54,   54,  253,  141,
      253,   54,  140,   54,   54,  253,  253,  142,  253,  253,
      253,  139,   54,   54,  253,   54,  253,  253,   54,  253,
      253,  253,   54,  253,  253,  141,   54,  253,   96,   54,
       96,   96,   96,   96,   54,  253,   54,   54,   97,  253,
       96,   96,   96,   96,   96,   96,  253,  145,  253,   54,
       97,  253,  253,   96,   54,   54,   54,   54,   54,  144,
       54,  146,   54,  253,  253,  253,   54,  253,  152,   54,

      147,  253,  145,  153,   54,  253,  253,   54,   54,   54,
      253,   54,  148,   54,   54,  144,   54,  146,   54,   54,
       54,  253,   54,   54,  152,   54,  147,   54,  149,  153,
      253,  151,   54,   54,  253,   54,  150,  148,  253,  253,
       54,   54,  253,   54,   54,  253,   54,   54,   54,  154,
      253,   54,  253,   54,  149,   54,   54,  151,   54,   54,
      156,   54,  150,   54,  253,   54,  158,  155,  253,  253,
      253,   54,   54,  157,   54,  154,   54,   54,   54,   54,
       54,  253,   54,   54,   54,   54,  156,  253,  159,   54,
      253,  160,  158,  155,   54,   54,   54,  253,  157,  253,

       54,   54,   54,   54,   54,   54,  165,   54,   54,  163,
      161,  253,  253,  159,  253,   54,  253,  160,   54,   54,
      253,   54,   54,  162,  253,   54,   54,   54,   54,  164,
      253,   54,  165,   54,  166,  163,  161,  253,   54,   54,
       54,   54,  253,  253,   54,  169,  253,   54,  162,  167,
       54,   54,   54,  253,   54,  164,   54,   54,  253,   54,
      166,   54,  253,   54,  253,   54,  168,   54,  170,   54,
       54,  169,  253,  171,  253,  167,   54,   54,   54,   54,
      173,  253,   54,   54,   54,  172,   54,   54,  253,   54,
       54,  174,  168,   54,  170,   54,   54,  253,   54,  171,

       54,   54,   54,  253,   54,  253,  173,   54,   54,   54,
      253,  172,  253,   54,   54,   54,   54,  174,   54,   54,
      178,  253,  253,   54,  253,   54,  253,  175,   54,   54,
      253,  176,   54,  253,   54,   54,   54,   54,  253,   54,
       54,  253,   54,  179,  177,   54,  178,   54,   54,  253,
      253,  253,  175,   54,   54,   54,  176,   54,  253,   54,
      253,   54,  253,   54,   54,   54,  253,   54,   54,  179,
      177,  180,  181,   54,   54,   54,  253,  253,  253,   54,
      253,   54,   54,  253,  253,   54,  253,  253,  253,  253,
      253,  253,   54,   54,   54,  253,  180,  181,   54,  253,

       54,   54,   54,   96,   54,   96,   96,   96,   96,  184,
      185,   54,  253,   97,   54,  186,   96,  187,   54,  253,
       54,   54,   54,  253,   54,   54,  253,   54,   54,   54,
      253,   54,   54,   54,  184,  253,  185,   54,  183,   54,
      188,  186,  187,   54,  253,   54,   54,   54,  189,   54,
      253,   54,   54,   54,  253,   54,   54,  253,   54,   54,
       54,   54,   54,  183,  192,  188,  253,  191,  190,  253,
       54,   54,   54,  189,   54,  253,  253,   54,   54,  253,
       54,   54,   54,  253,   54,  253,   54,   54,   54,  253,
      192,   54,   54,  191,  190,   54,  253,   54,   54,   54,

       54,  253,   54,  253,   54,   54,   54,   54,  195,   54,
      193,  194,   54,  253,  253,   54,   54,   54,  253,   54,
       54,   54,   54,  196,   54,   54,   54,  253,   54,  253,
       54,  253,   54,   54,  195,  193,   54,  194,   54,  253,
       54,   54,  253,   54,   54,   54,  197,   54,  196,   54,
      253,  253,  253,   54,  253,  253,   54,   54,  198,   54,
      253,   54,   54,   54,   54,   54,  253,   54,  253,   54,
      200,  197,  201,   54,   54,   54,  253,  199,   54,  253,
      253,   54,  253,  198,   54,   54,   54,  253,   54,  253,
       54,   54,  253,   54,   54,   54,  200,  253,  201,   54,

       54,   54,  199,   54,  203,   54,   54,  202,  205,   54,
       54,  253,  253,  253,  253,  206,   54,  253,   54,   54,
       54,  204,  253,   54,   54,   54,   54,  253,   54,   54,
      203,   54,   54,  202,  205,   54,   54,  253,   54,  253,
      253,  206,   54,   54,  253,  253,  204,  209,   54,   54,
       54,   54,   96,   54,   96,   96,   96,   96,   54,   54,
       54,   54,   97,   54,   54,   96,  253,   54,  253,   54,
      253,  210,  253,  209,  208,  211,   54,  253,  253,   54,
      212,  253,  253,   54,  253,   54,  253,   54,   54,  253,
      207,   54,   54,  253,  253,   54,   54,  210,   54,  208,

      253,  211,   54,   54,   54,   54,  212,   54,   54,  253,
      213,  253,  253,   54,  253,  207,   54,  253,   54,   54,
       54,   54,  253,   54,   54,   54,   54,  253,   54,   54,
      253,   54,   54,  215,   54,   54,  213,   54,  253,   54,
      253,  214,  253,   54,  253,   54,   54,   54,   54,  253,
       54,  253,   54,   54,  253,   54,  253,   54,   54,  215,
      253,   54,  216,   54,   54,  219,  214,   54,  217,   54,
       54,   54,  218,   54,  253,  253,  253,  253,   54,   54,
       54,  253,   54,  220,   54,   54,   54,  216,  253,   54,
       54,  219,   54,  253,  217,   54,   54,  218,  253,   54,

      253,  253,   54,   54,  253,   54,   54,   54,  220,  253,
       54,  253,   54,  253,   54,   54,   96,   54,   96,   96,
       96,   96,   54,  253,   54,   54,   97,   54,   54,   96,
       54,   54,  253,   54,  222,   54,  253,   54,  221,   54,
      253,  253,  253,   54,  253,   54,  223,   54,   54,  253,
       54,   54,   54,   54,  253,   54,   54,   54,  253,   54,
      222,   54,   54,  253,  253,   54,   54,  253,   54,   54,
       54,   54,  223,   54,   54,   54,  253,   54,  224,   54,
       54,  253,  253,   54,   54,  253,   54,   54,  253,   54,
      253,   54,   54,   54,  253,   54,  225,   54,   54,   54,

      253,  226,   54,  229,  253,  227,  253,   54,  228,  253,
       54,   54,  253,   54,   54,   54,   54,   54,  253,   54,
      253,  253,  225,   54,  253,   54,  226,  230,  253,  229,
       54,  227,   54,  253,  228,   54,   54,   54,   54,   54,
      253,   54,  231,   54,   54,  253,  234,  253,   54,  253,
       54,  253,  232,  230,   54,   54,  253,  253,   54,   54,
       54,  253,   54,  233,   54,   54,   54,   54,  231,  235,
       54,  253,  234,  253,   54,  253,   54,  232,  253,  253,
       54,  253,  236,   54,   54,  253,  253,   54,  233,  253,
       54,   54,  253,   54,  235,   54,  237,  238,   54,   54,

       54,  242,  253,  253,  253,   54,  253,  236,  239,  253,
       54,  240,   54,  253,  253,  253,   54,  253,   54,  253,
       54,   54,  237,  238,   54,   54,   54,  242,   54,   54,
      253,   54,   54,  253,  239,   54,  253,  240,  241,   54,
      243,  248,  244,   54,  253,   54,   54,  253,   54,   54,
       54,  253,   54,  253,   54,   54,   54,  253,   54,   54,
       54,   54,  253,  253,  241,   54,  243,  248,  244,  245,
      246,   54,  247,   54,   54,  253,   54,   54,  253,  253,
       54,   54,   54,  250,   54,  253,   54,   54,   54,  253,
      253,   54,  249,   54,  245,   54,  246,   54,  247,  253,

      253,   54,  253,   54,  251,   54,   54,  253,   54,  250,
      253,   54,  253,   54,   54,   54,   54,  253,  249,   54,
      253,   54,   54,  253,  253,  253,  252,  253,   54,  253,
      251,   54,  253,   54,  253,  253,  253,   54,   54,  253,
       54,  253,   54,  253,  253,  253,  253,  253,   54,  253,
      253,  252,  253,  253,  253,  253,   54,  253,  253,  253,
      253,  253,  253,  253,  253,  253,  253,   54,   39,   39,
       39,   45,   45,   45,   95,   95,   96,   96,    5,  253,
      253,  253,  253,  253,  253,  253,  253,  253,  253,  253,
      253,  253,  253,  253,  253,  253,  253,  253,  253,  253,

      253,  253,  253,  253,  253,  253,  253,  253,  253,  253,
      253,  253,  253,  253,  253,  253,  253,  253,  253,  253,
      253,  253,  253,  253,  253,  253,  253,  253,  253,  253,
      253,  253,  253,  253,  253,  253,  253,  253,  253,  253,
      253,  253,  253,  253,  253,  253,  253
    } ;

static const flex_int16_t yy_chk[1848] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,   13,   15,
       13,   14,   14,   15,   14,   16,   17,   16,   18,   42,
      257,   17,   17,   18,   19,   47,   94,   47,   42,  255,
      182,   19,   19,   19,   19,   19,   19,   53,   52,   19,

       19,   19,   51,   19,   22,   98,   21,   98,   22,   21,
       49,   94,   45,   43,   42,   19,   21,   41,   40,   21,
       19,   22,   12,   19,   10,    9,   21,    7,   22,   19,
       22,    6,   21,    5,   22,   21,   94,    4,   50,    3,
       50,   19,   21,   23,   21,   19,   22,   50,   19,   20,
       26,   21,   23,   22,   26,   29,   20,   20,   20,   20,
       20,   20,   23,   23,   20,   20,   20,    0,   24,   23,
       25,   20,   24,   50,   26,   29,   26,    0,   23,   24,
       26,   29,    0,   25,    0,   24,   27,   23,   23,    0,
       25,   20,   24,   28,   24,   27,   25,   20,   24,   26,

       29,    0,    0,   28,    0,   24,   27,    0,   25,    0,
       24,    0,   27,   28,   30,   25,   20,   24,   30,   28,
        0,   27,   31,   32,   30,    0,   31,   33,    0,   28,
       31,   27,   32,    0,   30,    0,   32,   33,   28,    0,
       30,    0,    0,   32,   30,    0,   31,   33,   31,   32,
       30,  143,   31,   33,   34,   36,   31,   34,   32,   30,
       35,   32,   54,   33,   35,    0,   36,    0,   32,   34,
       34,   31,   33,    0,   34,   36,    0,   35,    0,  143,
       34,   36,   54,   34,   35,    0,   35,   37,   54,    0,
       35,   37,   36,    0,   34,   34,    0,    0,   38,   34,

       36,   38,   35,    0,  143,    0,    0,   54,    0,   35,
        0,   37,    0,   37,   60,    0,    0,   37,   38,   55,
        0,   56,   56,    0,   38,    0,    0,   38,   48,   55,
       48,   48,   48,   48,   60,    0,   37,   56,   48,   55,
       60,   48,   56,   38,   57,   55,   57,   56,   56,   58,
        0,   58,    0,   63,   59,   55,   59,   61,    0,   60,
        0,   61,   56,    0,   55,    0,   57,   56,    0,   58,
       57,    0,   57,   63,   59,   58,   62,   58,    0,   63,
       59,   61,   59,   61,   62,   64,    0,   61,    0,    0,
        0,   57,   62,   66,   58,    0,   62,    0,   63,   59,

       64,    0,   62,   66,    0,   64,   61,    0,   65,    0,
       62,   64,    0,   66,    0,   65,   67,   62,    0,   66,
       67,   62,   65,    0,    0,   64,    0,    0,   65,   66,
       64,    0,   68,    0,   65,   70,   68,   69,   66,    0,
       67,   65,   67,   68,   69,   70,   67,   65,    0,    0,
        0,    0,   68,   65,    0,   70,    0,   69,   68,    0,
        0,   70,   68,   69,   71,   67,   72,    0,   73,   68,
       69,   70,    0,   77,   71,    0,   72,   68,    0,    0,
       70,   77,   69,    0,   71,   73,   72,    0,   73,    0,
       71,    0,   72,   77,   73,   79,   74,   76,    0,   77,

       71,   76,   72,   74,   75,   75,    0,   77,   78,   71,
       73,   72,   78,   73,   79,   79,   74,   76,   77,   75,
       75,   79,   74,   76,    0,   75,   80,   76,   81,   74,
       75,   75,   78,    0,   78,   80,    0,    0,   78,   79,
       79,   74,   76,    0,   75,   75,   80,    0,   81,    0,
       75,    0,   80,    0,   81,   82,   82,   78,   83,   84,
       85,   80,    0,    0,   86,   83,   84,   84,   86,    0,
       85,   80,    0,   81,   84,    0,   82,    0,   83,   84,
       85,   82,   82,    0,   83,   84,   85,    0,   86,   87,
       86,   83,   84,   84,   86,   88,   85,   87,   88,   84,

       89,   82,    0,   83,   84,   85,   90,   90,    0,   87,
        0,   92,    0,   86,    0,   87,   89,    0,   88,    0,
       89,   88,   91,   87,   88,    0,   89,   90,    0,   91,
        0,   92,   90,   90,   87,    0,    0,   92,    0,    0,
        0,   89,   91,   88,    0,   89,    0,    0,   91,    0,
        0,    0,   90,    0,    0,   91,   92,    0,   95,  100,
       95,   95,   95,   95,   99,    0,  102,   91,   95,    0,
       97,   95,   97,   97,   97,   97,    0,   99,    0,  100,
       97,    0,    0,   97,   99,  100,  102,  101,  103,   97,
       99,  101,  102,    0,    0,    0,  104,    0,  109,  105,

      104,    0,   99,  110,  100,    0,    0,  101,  103,   99,
        0,  102,  105,  101,  103,   97,  104,  101,  109,  105,
      106,    0,  104,  110,  109,  105,  104,  107,  106,  110,
        0,  108,  101,  103,    0,  108,  107,  105,    0,    0,
      106,  104,    0,  109,  105,    0,  106,  107,  110,  111,
        0,  111,    0,  107,  106,  108,  112,  108,  114,  115,
      113,  108,  107,  113,    0,  106,  115,  112,    0,    0,
        0,  111,  107,  114,  116,  111,  112,  111,  114,  115,
      108,    0,  112,  113,  114,  115,  113,    0,  116,  113,
        0,  117,  115,  112,  116,  117,  111,    0,  114,    0,

      116,  112,  118,  114,  115,  120,  122,  119,  113,  120,
      118,    0,    0,  116,    0,  117,    0,  117,  121,  116,
        0,  117,  118,  119,    0,  120,  122,  119,  118,  121,
        0,  120,  122,  119,  123,  120,  118,    0,  121,  124,
      117,  126,    0,    0,  121,  126,    0,  118,  119,  124,
      120,  122,  119,    0,  123,  121,  128,  125,    0,  124,
      123,  126,    0,  121,    0,  124,  125,  126,  127,  127,
      129,  126,    0,  130,    0,  124,  128,  125,  131,  123,
      132,    0,  128,  125,  124,  131,  126,  133,    0,  127,
      129,  133,  125,  130,  127,  127,  129,    0,  131,  130,

      132,  128,  125,    0,  131,    0,  132,  133,  134,  135,
        0,  131,    0,  133,  127,  129,  136,  133,  130,  137,
      139,    0,    0,  131,    0,  132,    0,  135,  134,  135,
        0,  136,  133,    0,  134,  135,  136,  138,    0,  137,
      139,    0,  136,  140,  138,  137,  139,  140,  146,    0,
        0,    0,  135,  134,  135,  141,  136,  138,    0,  142,
        0,  136,    0,  138,  137,  139,    0,  140,  146,  140,
      138,  141,  142,  140,  146,  141,    0,    0,    0,  142,
        0,  141,  138,    0,    0,  142,    0,    0,    0,    0,
        0,    0,  140,  146,  145,    0,  141,  142,  148,    0,

      141,  147,  150,  144,  142,  144,  144,  144,  144,  145,
      147,  149,    0,  144,  145,  149,  144,  150,  148,    0,
      145,  147,  150,    0,  148,  151,    0,  147,  150,  152,
        0,  149,  154,  153,  145,    0,  147,  149,  144,  145,
      151,  149,  150,  148,    0,  151,  147,  150,  153,  152,
        0,  151,  154,  153,    0,  152,  149,    0,  154,  153,
      155,  156,  157,  144,  159,  151,    0,  158,  156,    0,
      151,  158,  161,  153,  152,    0,    0,  154,  153,    0,
      155,  156,  157,    0,  159,    0,  155,  156,  157,    0,
      159,  158,  161,  158,  156,  160,    0,  158,  161,  163,

      162,    0,  164,    0,  165,  155,  156,  157,  163,  159,
      160,  162,  167,    0,    0,  160,  158,  161,    0,  163,
      162,  160,  164,  165,  165,  163,  162,    0,  164,    0,
      165,    0,  167,  166,  163,  160,  168,  162,  167,    0,
      160,  170,    0,  169,  163,  162,  166,  164,  165,  165,
        0,    0,    0,  166,    0,    0,  168,  167,  169,  166,
        0,  170,  168,  169,  171,  174,    0,  170,    0,  169,
      172,  166,  173,  172,  173,  175,    0,  171,  166,    0,
        0,  168,    0,  169,  171,  174,  170,    0,  169,    0,
      171,  174,    0,  172,  173,  175,  172,    0,  173,  172,

      173,  175,  171,  176,  177,  178,  179,  176,  180,  171,
      174,    0,    0,    0,    0,  181,  184,    0,  172,  173,
      175,  179,    0,  176,  177,  178,  179,    0,  180,  176,
      177,  178,  179,  176,  180,  181,  184,    0,  185,    0,
        0,  181,  184,  187,    0,    0,  179,  188,  176,  177,
      178,  179,  183,  180,  183,  183,  183,  183,  185,  186,
      181,  184,  183,  187,  185,  183,    0,  188,    0,  187,
        0,  189,    0,  188,  186,  190,  191,    0,    0,  186,
      191,    0,    0,  185,    0,  186,    0,  192,  187,    0,
      183,  189,  188,    0,    0,  190,  191,  189,  193,  186,

        0,  190,  191,  194,  186,  196,  191,  192,  195,    0,
      195,    0,    0,  192,    0,  183,  189,    0,  193,  198,
      190,  191,    0,  194,  193,  196,  197,    0,  195,  194,
        0,  196,  192,  200,  195,  199,  195,  200,    0,  198,
        0,  197,    0,  193,    0,  198,  197,  201,  194,    0,
      196,    0,  197,  195,    0,  199,    0,  200,  203,  200,
        0,  199,  201,  200,  198,  204,  197,  201,  202,  205,
      202,  197,  203,  201,    0,    0,    0,    0,  203,  206,
      199,    0,  200,  205,  203,  204,  208,  201,    0,  205,
      202,  204,  201,    0,  202,  205,  202,  203,    0,  206,

        0,    0,  209,  203,    0,  206,  208,  210,  205,    0,
      204,    0,  208,    0,  205,  202,  207,  211,  207,  207,
      207,  207,  209,    0,  206,  212,  207,  210,  209,  207,
      213,  208,    0,  210,  212,  214,    0,  211,  211,  216,
        0,    0,    0,  211,    0,  212,  215,  209,  215,    0,
      213,  212,  210,  218,    0,  214,  213,  217,    0,  216,
      212,  214,  211,    0,    0,  216,  219,    0,  215,  220,
      212,  222,  215,  218,  215,  213,    0,  217,  217,  218,
      214,    0,    0,  217,  216,    0,  219,  221,    0,  220,
        0,  222,  219,  215,    0,  220,  221,  222,  218,  223,

        0,  221,  217,  225,    0,  223,    0,  221,  224,    0,
      224,  219,    0,  221,  220,  227,  222,  226,    0,  223,
        0,    0,  221,  225,    0,  223,  221,  226,    0,  225,
      224,  223,  221,    0,  224,  227,  224,  226,  229,  228,
        0,  227,  228,  226,  223,    0,  231,    0,  225,    0,
      230,    0,  229,  226,  232,  224,    0,    0,  229,  228,
      227,    0,  226,  230,  229,  228,  231,  233,  228,  232,
      230,    0,  231,    0,  232,    0,  230,  229,    0,    0,
      232,    0,  233,  229,  228,    0,    0,  233,  230,    0,
      235,  231,    0,  233,  232,  230,  234,  235,  234,  232,

      236,  239,    0,    0,    0,  237,    0,  233,  236,    0,
      235,  237,  233,    0,    0,    0,  235,    0,  234,    0,
      236,  239,  234,  235,  234,  237,  236,  239,  238,  240,
        0,  237,  241,    0,  236,  235,    0,  237,  238,  245,
      240,  245,  241,  234,    0,  236,  239,    0,  238,  240,
      237,    0,  241,    0,  238,  240,  242,    0,  241,  245,
      243,  244,    0,    0,  238,  245,  240,  245,  241,  242,
      243,  247,  244,  238,  240,    0,  242,  241,    0,    0,
      243,  244,  242,  248,  245,    0,  243,  244,  246,    0,
        0,  247,  246,  250,  242,  249,  243,  247,  244,    0,

        0,  242,    0,  248,  249,  243,  244,    0,  246,  248,
        0,  251,    0,  250,  246,  249,  247,    0,  246,  250,
        0,  249,  252,    0,    0,    0,  251,    0,  248,    0,
      249,  251,    0,  246,    0,    0,    0,  251,  250,    0,
      249,    0,  252,    0,    0,    0,    0,    0,  252,    0,
        0,  251,    0,    0,    0,    0,  251,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,  252,  254,  254,
      254,  256,  256,  256,  258,  258,  259,  259,  253,  253,
      253,  253,  253,  253,  253,  253,  253,  253,  253,  253,
      253,  253,  253,  253,  253,  253,  253,  253,  253,  253,

      253,  253,  253,  253,  253,  253,  253,  253,  253,  253,
      253,  253,  253,  253,  253,  253,  253,  253,  253,  253,
      253,  253,  253,  253,  253,  253,  253,  253,  253,  253,
      253,  253,  253,  253,  253,  253,  253,  253,  253,  253,
      253,  253,  253,  253,  253,  253,  253
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "lex.l"
#line 2 "lex.l"
    /* keywords are case insensitive */
    /* we don't need yywrap() function */
    /* we don't need yyunput() function */
    /* we don't need input() function */
#define YY_NO_INPUT 1
    /* enable location */
#include "ast.h"
#include "yacc.tab.h"
#include <iostream>

// automatically update location
#define YY_USER_ACTION \
    yylloc->first_line = yylloc->last_line; \
    yylloc->first_column = yylloc->last_column; \
    for (int i = 0; yytext[i] != '\0'; i++) { \
        if(yytext[i] == '\n') { \
            yylloc->last_line++; \
            yylloc->last_column = 1; \
        } else { \
            yylloc->last_column++; \
        } \
    }

#line 984 "/home/wangyiming/db2025-yoursql/src/parser/lex.yy.cpp"

#line 986 "/home/wangyiming/db2025-yoursql/src/parser/lex.yy.cpp"

#define INITIAL 0
#define STATE_COMMENT 1

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

YYSTYPE * yyget_lval ( void );

void yyset_lval ( YYSTYPE * yylval_param  );

       YYLTYPE *yyget_lloc ( void );
    
        void yyset_lloc ( YYLTYPE * yylloc_param  );
    
/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex \
               (YYSTYPE * yylval_param, YYLTYPE * yylloc_param );

#define YY_DECL int yylex \
               (YYSTYPE * yylval_param, YYLTYPE * yylloc_param )
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
        YYSTYPE * yylval;
    
        YYLTYPE * yylloc;
    
    yylval = yylval_param;

    yylloc = yylloc_param;

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 46 "lex.l"

#line 48 "lex.l"
    /* block comment */
#line 1224 "/home/wangyiming/db2025-yoursql/src/parser/lex.yy.cpp"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 254 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1779 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 49 "lex.l"
{ BEGIN(STATE_COMMENT); }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 50 "lex.l"
{ BEGIN(INITIAL); }
	YY_BREAK
case 3:
/* rule 3 can match eol */
YY_RULE_SETUP
#line 51 "lex.l"
{ /* ignore the text of the comment */ }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 52 "lex.l"
{ /* ignore *'s that aren't part of */ }
	YY_BREAK
/* single line comment */
case 5:
YY_RULE_SETUP
#line 54 "lex.l"
{ /* ignore single line comment */ }
	YY_BREAK
/* white space and new line */
case 6:
YY_RULE_SETUP
#line 56 "lex.l"
{ /* ignore white space */ }
	YY_BREAK
case 7:
/* rule 7 can match eol */
YY_RULE_SETUP
#line 57 "lex.l"
{ /* ignore new line */ }
	YY_BREAK
/* keywords */
case 8:
YY_RULE_SETUP
#line 59 "lex.l"
{ return SHOW; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 60 "lex.l"
{ return TXN_BEGIN; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 61 "lex.l"
{ return TXN_COMMIT; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 62 "lex.l"
{ return TXN_ABORT; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 63 "lex.l"
{ return TXN_ROLLBACK; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 64 "lex.l"
{ return TABLES; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 65 "lex.l"
{ return CREATE; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 66 "lex.l"
{ return TABLE; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 67 "lex.l"
{ return DROP; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 68 "lex.l"
{ return DESC; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 69 "lex.l"
{ return INSERT; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 70 "lex.l"
{ return INTO; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 71 "lex.l"
{ return VALUES; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 72 "lex.l"
{ return DELETE; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 73 "lex.l"
{ return FROM; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 74 "lex.l"
{ return WHERE; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 75 "lex.l"
{ return UPDATE; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 76 "lex.l"
{ return SET; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 77 "lex.l"
{ return SELECT; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 78 "lex.l"
{ return EXPLAIN; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 79 "lex.l"
{ return LOAD; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 80 "lex.l"
{ return INTO; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 81 "lex.l"
{ return INT; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 82 "lex.l"
{ return CHAR; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 83 "lex.l"
{ return FLOAT; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 84 "lex.l"
{return DATE; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 85 "lex.l"
{ return INDEX; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 86 "lex.l"
{ return AND; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 87 "lex.l"
{return JOIN;}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 88 "lex.l"
{return ON;}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 89 "lex.l"
{return SEMI;}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 90 "lex.l"
{return ANTI;}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 91 "lex.l"
{ return EXIT; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 92 "lex.l"
{ return HELP; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 93 "lex.l"
{ return COUNT; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 94 "lex.l"
{ return MAX; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 95 "lex.l"
{ return MIN; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 96 "lex.l"
{ return SUM; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 97 "lex.l"
{ return AVG; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 98 "lex.l"
{ return AS; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 99 "lex.l"
{ return HAVING; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 100 "lex.l"
{ return GROUP; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 101 "lex.l"
{ return ORDER; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 102 "lex.l"
{ return LIMIT; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 103 "lex.l"
{  return BY;  }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 104 "lex.l"
{ return ASC; }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 105 "lex.l"
{ return ENABLE_NESTLOOP; }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 106 "lex.l"
{ return ENABLE_SORTMERGE; }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 107 "lex.l"
{ return STATIC_CHECKPOINT; }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 108 "lex.l"
{ 
    yylval->sv_bool = true;
    return VALUE_BOOL; 
}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 112 "lex.l"
{
    yylval->sv_bool = false;
    return VALUE_BOOL;
}
	YY_BREAK
/* operators */
case 59:
YY_RULE_SETUP
#line 117 "lex.l"
{ return GEQ; }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 118 "lex.l"
{ return LEQ; }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 119 "lex.l"
{ return NEQ; }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 120 "lex.l"
{ yylval->sv_char = '+'; return OP_PLUS; }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 121 "lex.l"
{ yylval->sv_char = '-'; return OP_MINUS; }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 123 "lex.l"
{ yylval->sv_char = '/'; return OP_DIVIDE; }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 124 "lex.l"
{ return yytext[0]; }
	YY_BREAK
/* literals */
case 66:
YY_RULE_SETUP
#line 127 "lex.l"
{
    yylval->sv_int = atoi(yytext);
    return VALUE_INT;
}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 131 "lex.l"
{
    yylval->sv_float = atof(yytext);
    return VALUE_FLOAT;
}
	YY_BREAK
case 68:
/* rule 68 can match eol */
YY_RULE_SETUP
#line 135 "lex.l"
{
    yylval->sv_str = std::string(yytext + 1, strlen(yytext) - 2);
    return VALUE_STRING;
}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 139 "lex.l"
{
    yylval->sv_str = std::string(yytext);
    return VALUE_PATH;
}
	YY_BREAK
/* id */
case 70:
YY_RULE_SETUP
#line 144 "lex.l"
{
    yylval->sv_str = yytext;
    return IDENTIFIER;
}
	YY_BREAK
/* EOF */
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(STATE_COMMENT):
#line 150 "lex.l"
{ return T_EOF; }
	YY_BREAK
/* unexpected char */
case 71:
YY_RULE_SETUP
#line 152 "lex.l"
{ std::cerr << "Lexer Error: unexpected character " << yytext[0] << std::endl; }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 153 "lex.l"
ECHO;
	YY_BREAK
#line 1678 "/home/wangyiming/db2025-yoursql/src/parser/lex.yy.cpp"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 254 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 254 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 253);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 153 "lex.l"


